Importar o pacote **pandas** (já disponível no colab)

In [68]:
import pandas as pd
pd.options.mode.chained_assignment = None

**Series** representam um *array* de valores

In [8]:
notas = pd.Series([10.0, 7.5, 8.5, 9.0])

Algumas funções executadas para **Series**

In [10]:
print(f'Primeira nota: {notas[0]}')
print(f'Úmtima nota: {notas.iloc[-1]}')
print(f'Total: {notas.sum()}')
print(f'Média: {notas.mean()}')
print(f'Máximo: {notas.max()}')
print(f'Mínimo: {notas.min()}')

Primeira nota: 10.0
Úmtima nota: 9.0
Total: 35.0
Média: 8.75
Máximo: 10.0
Mínimo: 7.5

**Dataframes** representam uma matriz com linhas e colunas, semelhante a uma planilha **Excel**

In [13]:
dados = {
    "nome": ["Ana", "Bruno", "Carlos"],
    "idade": [20, 22, 21],
    "curso": ["SI", "CC", "SI"]
}

df = pd.DataFrame(dados)
df

     nome  idade curso
0     Ana     20    SI
1   Bruno     22    CC
2  Carlos     21    SI

Algumas funções sobre **Dataframes**

In [15]:
df.columns

Index(['nome', 'idade', 'curso'], dtype='object')

In [16]:
df.shape

(3, 3)

In [19]:
df.head(1)

  nome  idade curso
0  Ana     20    SI

In [20]:
df.tail(1)

     nome  idade curso
2  Carlos     21    SI

Obter arquivo para testes publicado em um **repo git**

In [35]:
!wget https://raw.githubusercontent.com/esensato/ssa-2026-01/refs/heads/main/entrada.csv

--2026-03-02 21:22:04--  https://raw.githubusercontent.com/esensato/ssa-2026-01/refs/heads/main/entrada.csv
Resolving raw.githubusercontent.com (raw.githubusercontent.com)... 185.199.108.133, 185.199.109.133, 185.199.110.133, ...
Connecting to raw.githubusercontent.com (raw.githubusercontent.com)|185.199.108.133|:443... connected.
HTTP request sent, awaiting response... 200 OK
Length: 688 [text/plain]
Saving to: ‘entrada.csv’

entrada.csv         100%[===================>]     688  --.-KB/s    in 0s

2026-03-02 21:22:04 (29.8 MB/s) - ‘entrada.csv’ saved [688/688]

Lendo arquivo **csv** com **Pandas**

In [36]:
df = pd.read_csv("entrada.csv")
df

,id_pedido,id_cliente,nome,data,produto,quantidade,preco,total,sistema_origem
0,1001,C001,João Silva,2023-01-05,Notebook,1,3500.0,3500.0,ERP
1,1002,C002,Maria Souza,05/01/2023,Mouse,2,50.0,100.0,ERP
2,1003,C002,Maria Souza,2023/01/06,Mouse,2,50.0,100.0,API
3,1003,C002,Maria Souza,2023/01/06,Mouse,2,50.0,100.0,API
4,1004,NaN,Carlos Lima,2023-01-07,Teclado,0,120.0,120.0,Planilha
5,1005,C004,ANA PEREIRA,07-01-2023,Monitor,-,899.0,899.0,Planilha
6,1006,C005,Pedro Santos,2023-01-08,monitor,1,899.0,899.0,NaN
7,1007,C006,Pedro Santos,2023-01-08,Cadeira Gamer,1,1200.5,1200.5,ERP
8,1008,C006,Pedro SANTOS,2023-01-08,Cadeira Gamer,1,1200.5,1200.5,ERP
9,1009,C007,Marcos Oliveira,2023-01-08,Teclado,2,120.0,240.0,NaN

Obter colunas específicas do **Dataframe** importado

In [24]:
df[["nome", "sistema_origem"]]

              nome sistema_origem
0      João Silva             ERP
1      Maria Souza            ERP
2      Maria Souza            API
3      Maria Souza            API
4      Carlos Lima       Planilha
5      ANA PEREIRA       Planilha
6     Pedro Santos            NaN
7     Pedro Santos            ERP
8     Pedro SANTOS            ERP
9  Marcos Oliveira            NaN

Obter valores únicos, total de itens e somatória (veja que estará errado pois nem todos valores são numéricos!)

In [37]:
print(df["sistema_origem"].unique())
print(df["id_cliente"].count())
print(df["quantidade"].sum())

['ERP' 'API' 'Planilha' nan]
9
 12220-1112

Removendo espaços extras com **strip**

In [38]:
df["id_cliente"] = df["id_cliente"].str.strip()
df["nome"] = df["nome"].str.strip()

Padronizando maiúsculo / minúsculo

In [39]:
df["nome"] = df["nome"].str.title()
df["sistema_origem"] = df["sistema_origem"].str.upper()
df["produto"] = df["produto"].str.upper()

Remover dados faltantes, por exemplo **id_cliente**

In [63]:
df = df.dropna(subset="id_cliente")

Trabalhando números tratados como texto, por exemplo na quantidade

In [69]:
df["quantidade"] = pd.to_numeric(df["quantidade"], errors="coerce")
df = df.dropna(subset="quantidade")

Criar uma função para trabalhar as datas em diversos formatos

In [47]:
def parse_data(valor):
  formatos = ["%Y-%m-%d", "%d/%m/%Y", "%Y/%m/%d"]
  for f in formatos:
    try:
      return pd.to_datetime(valor, format=f)
    except:
      pass
  return pd.NaT

Aplicar a função **parse_data** e eliminar as linhas fora do padrão

In [55]:
df['data'] = df['data'].apply(parse_data)
df = df.dropna(subset="data")

Removendo linhas duplicadas (por exemplo linhas 2 e 3)

In [66]:
df = df.drop_duplicates()
df

,id_pedido,id_cliente,nome,data,produto,quantidade,preco,total,sistema_origem,total_calculado
1,1002,C002,Maria Souza,2023-01-05,MOUSE,2.0,50.0,100.0,ERP,100.0
2,1003,C002,Maria Souza,2023-01-06,MOUSE,2.0,50.0,100.0,API,100.0
6,1006,C005,Pedro Santos,2023-01-08,MONITOR,1.0,899.0,899.0,NaN,899.0
7,1007,C006,Pedro Santos,2023-01-08,CADEIRA GAMER,1.0,1200.5,1200.5,ERP,1200.5
8,1008,C006,Pedro Santos,2023-01-08,CADEIRA GAMER,1.0,1200.5,1200.5,ERP,1200.5
9,1009,C007,Marcos Oliveira,2023-01-08,TECLADO,2.0,120.0,240.0,NaN,240.0

Criando colunas derivadas, por exemplo, total como cálculo de quantidade * preco

In [67]:
df['total_calculado'] = df['quantidade'] * df['preco']
df

,id_pedido,id_cliente,nome,data,produto,quantidade,preco,total,sistema_origem,total_calculado
1,1002,C002,Maria Souza,2023-01-05,MOUSE,2.0,50.0,100.0,ERP,100.0
2,1003,C002,Maria Souza,2023-01-06,MOUSE,2.0,50.0,100.0,API,100.0
6,1006,C005,Pedro Santos,2023-01-08,MONITOR,1.0,899.0,899.0,NaN,899.0
7,1007,C006,Pedro Santos,2023-01-08,CADEIRA GAMER,1.0,1200.5,1200.5,ERP,1200.5
8,1008,C006,Pedro Santos,2023-01-08,CADEIRA GAMER,1.0,1200.5,1200.5,ERP,1200.5
9,1009,C007,Marcos Oliveira,2023-01-08,TECLADO,2.0,120.0,240.0,NaN,240.0